version: '3.3'
# KB_DB_TAG_VERSION=mytagversion docker-compose up
services:
      web:
        image: campnonet/landing-page
        ports:
          - 85:80
        restart: always
        volumes:
          - /var/www/html
        labels:
          - "traefik.enable=true"
          - "traefik.http.services.mesisamu.loadbalancer.server.port=80"
          - "traefik.http.routers.mesisamu.rule=Host(`mesisamu.com`)"
          - "traefik.http.routers.mesisamu.rule=Host(`www.mesisamu.com`)"
          - "traefik.http.routers.mesisamu.entrypoints=websecure"
          - "traefik.http.routers.mesisamu.tls.certresolver=production"
          - "traefik.http.routers.mesisamu.tls=true"
networks:
  default:
    external:
      name: traefik_default